// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAL0ZCM40-y51Z6P5C8AuUA3sNcDbM-Fc',
    appId: '1:403624567146:web:00c3b9e8b8f7f3cf4d0513',
    messagingSenderId: '403624567146',
    projectId: 'buzzychatapp-c12ab',
    authDomain: 'buzzychatapp-c12ab.firebaseapp.com',
    storageBucket: 'buzzychatapp-c12ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AjeEzDvlEKeXoK6_ttKsSfs_JT7D-3A',
    appId: '1:403624567146:android:2ef981dcea278f164d0513',
    messagingSenderId: '403624567146',
    projectId: 'buzzychatapp-c12ab',
    storageBucket: 'buzzychatapp-c12ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG7M90JUW2mO_M8vpu1dspD2_k9wwLGB4',
    appId: '1:403624567146:ios:d743ef135325a5e74d0513',
    messagingSenderId: '403624567146',
    projectId: 'buzzychatapp-c12ab',
    storageBucket: 'buzzychatapp-c12ab.appspot.com',
    iosBundleId: 'com.example.buzzyChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG7M90JUW2mO_M8vpu1dspD2_k9wwLGB4',
    appId: '1:403624567146:ios:21f73624ffdc1b1d4d0513',
    messagingSenderId: '403624567146',
    projectId: 'buzzychatapp-c12ab',
    storageBucket: 'buzzychatapp-c12ab.appspot.com',
    iosBundleId: 'com.example.buzzyChatapp.RunnerTests',
  );
}
